application: haiti-children
version: 1
runtime: go
api_version: go1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /html
  static_dir: html
  login: required
  auth_fail_action: redirect

- url: /images
  static_dir: images

- url: /javascript
  static_dir: javascript

- url: /.*
  script: _go_app
  #login: required
  #secure: always
  #auth_fail_action: redirect
