application: haiti-children
version: 1
runtime: go
api_version: go1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /css
  static_dir: css

- url: /html
  static_dir: html

- url: /images
  static_dir: images

- url: /.*
  script: _go_app
  #login: required
  #secure: always
  #auth_fail_action: redirect
